# Generated by Django 5.1.5 on 2025-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_service_image'),
        ('api', '0005_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='workers', to='admin_app.service'),
        ),
    ]
