# Generated by Django 5.1.5 on 2025-01-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_slot_options_alter_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
