# Generated by Django 5.1.5 on 2025-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_latitude_user_longitude_worker_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
