# Generated by Django 5.1.5 on 2025-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_latitude_remove_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='longitude',
        ),
    ]
