# Generated by Django 5.1.5 on 2025-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_worker_latitude_remove_worker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='off_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='worker',
            name='slot_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='worker',
            name='working_hours_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='worker',
            name='working_hours_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
