# Generated by Django 5.1.5 on 2025-02-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_worker_off_days_worker_slot_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='off_days',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='working_hours_start',
        ),
    ]
