# Generated by Django 5.1.5 on 2025-02-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_slot_options_alter_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('worker', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='off_days',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='working_hours_start',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
    ]
