# Generated by Django 5.1.5 on 2025-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_slot_options_alter_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='worker',
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['worker', 'start_time', 'end_time'], name='api_slot_worker__c79832_idx'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
