# Generated by Django 5.1.5 on 2025-02-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
