# Generated by Django 5.1.5 on 2025-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='worker',
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='api_slot_worker__c79832_idx',
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('worker', 'start_time', 'end_time'), name='unique_worker_slot'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
