# Generated by Django 5.1.5 on 2025-02-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
