# Generated by Django 5.1.5 on 2025-02-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
