# Generated by Django 5.1.5 on 2025-02-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
