# Generated by Django 5.1.5 on 2025-02-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
