# Generated by Django 5.1.5 on 2025-02-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
