# Generated by Django 5.1.5 on 2025-02-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_booking_platform_fee_booking_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
