# Generated by Django 5.1.5 on 2025-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_booking_platform_fee_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('workdone', 'Work Done'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
