# Generated by Django 5.1.5 on 2025-02-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
