# Generated by Django 5.1.5 on 2025-02-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_booking_platform_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
