# Generated by Django 5.1.5 on 2025-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
