# Generated by Django 5.1.5 on 2025-02-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_booking_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hours_worked',
        ),
    ]
