# Generated by Django 5.1.5 on 2025-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='insession',
            field=models.BooleanField(default=True),
        ),
    ]
