# Generated by Django 5.1.5 on 2025-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_roommember_insession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
