# Generated by Django 5.1.5 on 2025-02-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.worker')),
            ],
        ),
    ]
