# Generated by Django 5.1.5 on 2025-01-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
