# Generated by Django 5.1.5 on 2025-02-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='hourly_rate',
        ),
    ]
