# Generated by Django 5.1.5 on 2025-02-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_rename_price_service_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='hourly_rate',
            new_name='price',
        ),
    ]
