# Generated by Django 5.1.5 on 2025-02-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_hourly_rate_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='hourly_rate',
        ),
    ]
