# Generated by Django 5.1.5 on 2025-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_rename_hourly_rate_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
