# Generated by Django 5.1.5 on 2025-02-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_service_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hourly_rate',
        ),
    ]
