# Generated by Django 5.1.5 on 2025-02-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_remove_service_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='hourly_rate',
        ),
    ]
